### ISSUE TITLE
root is empty

### ISSUE THREAD

**Issue by vanyasem** [btactic/virtualmin-nginx-reverse-proxy-hook#1]
I might be missing a configuration option, but `root` is empty in the resulting nginx config:
`root ;`

Operating system | Ubuntu Linux 18.04.1
Webmin version | 1.893 
Usermin version | 1.741
Virtualmin version | 6.04

**Comment by adriangibanelbtactic** [comment]
Relevant code is:

https://github.com/btactic/virtualmin-nginx-reverse-proxy-hook/blob/master/virtualmin-nginx-hook#L137-L148

I recommend you to check if VIRTUALSERVER_PUBLIC_HTML_PATH variable has been replaced in newest virtualmins by a new variable.

**Comment by adriangibanelbtactic** [comment]
The issue was closed.
Reason: Lack of feedback.
