### ISSUE TITLE
The documentation left me confused

### ISSUE THREAD

**Issue by katz-kt** [btactic/virtualmin-nginx-reverse-proxy-hook#2]
Good day, am very new on Virtualmin apache and nginx configuration. I have tried to follow your intruction guess i must be failing at some point.

So i have installed nginx, chnaged apache port to 8080 and restarted apache. then I to follow your instruction. copied all the files and made a directory sites-available and site-enabled and then added the hook. 

The script works cause i see symbolic link in the directory and finaly I added include /etc/nginx/sites-enabled/*; on nginx config and restarted nginx

am getting and error of nginx can't start because ssl port is already in use. when i remove the ssl symbolic link conf files, i get nginx forbidden error via http protocal.

I think i mostly lost you here.

"## Specify custom nginx template
You can specify a custom nginx template for a virtualserver.
 You only have to set the description of the virtualserver using this pattern:
```
[nginx-template custom-template-name]
```
 With previous example (if default script config is not modified), the following files must exists:
```
/usr/local/etc/nginx-templates/custom-template-name/plantilla-nginx-ssl.conf
/usr/local/etc/nginx-templates/custom-template-name/plantilla-nginx.conf
```
 If custom template is not found, default template will be used instead."

Do i have to eddit anything on nginx config file or something please?

Thanks in advance.

**Comment by adriangibanelbtactic** [comment]
What's your distro?

> finaly I added include /etc/nginx/sites-enabled/*; on nginx config and restarted nginx

Why do you even added that include in the first place?
Usually your distro should have that part included.

> So i have installed nginx, chnaged apache port to 8080 and restarted apache.

You also need to change apache port 443 to 8443.

**Comment by adriangibanelbtactic** [comment]
The issue was closed.
Reason: Lack of feedback.
