### ISSUE TITLE
Hey, thanks for posting this - Couple of questions for you.

### ISSUE THREAD

**Issue by conandrum** [btactic/virtualmin-nginx-reverse-proxy-hook#3]
**1**. I did not change anything logrotation. So when I went to vreate a new virtual server, I got this:
Setting up log file rotation ..
.. Log file rotation failed! : .. the log file /var/log/virtualmin/blahblah.com_access_log is already being rotated at ../web-lib-funcs.pl line 1478.
**I guess I can ignore this right?** Its just informational?

**2**. Also i get this:
Applying Nginx configuration ..
.. restart failed :
...
Post-creation command failed : nginx.service is not active, cannot reload.
And the reason for the above is this:
nginx -t -c /etc/nginx/nginx.conf
nginx: [emerg] invalid number of arguments in "root" directive in /etc/nginx/sites-enabled/blahblah.com.conf:4
nginx: configuration file /etc/nginx/nginx.conf test failed

**I have to manually fill in the root path and restart nginx.**

**3**. When I access the site port 80, I get the access log ok, 
164.215.9.121 - - [11/May/2019:02:46:39 +0000] "GET / HTTP/1.1" 200 4922 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
164.215.9.121 - - [11/May/2019:02:46:40 +0000] "POST /mod_pagespeed_beacon?url=http%3A%2F%2F134.209.247.233%2F HTTP/1.1" 204 0 "http://134.209.247.233/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"

**but the page I see is the Apache default page??!!!**

Very new to this, but I can see that my VHost is not delivering.
**Where did I go wrong? Can you help please?**

Thank you

**Comment by adriangibanelbtactic** [comment]
I'm sorry I won't be able to give you any feedback with such a poor described issue.

You need to specify step-by-step what you originally had, what you then did, what you expected to happen and finally what happened instead.

Thank you.

**Comment by conandrum** [comment]
I gave up in the end. May try again in the future.
Thanks for replying.

PS. Is your module still working with the latest versions of Virtualmin?

**Comment by adriangibanelbtactic** [comment]
> PS. Is your module still working with the latest versions of Virtualmin?

No idea. We are not using it any more.
